name: Radar Army Update

on:
  schedule:
    # S'exécute toutes les heures (00:00, 01:00, etc.)
    - cron: '0 * * * *'
  workflow_dispatch: # Permet de le lancer manuellement depuis l'interface GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run Radar Army
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          npx tsx services/scrapers/bcge_scraper.ts
          npx tsx services/scrapers/bsharpe_scraper.ts
          npx tsx services/scrapers/change_geneve_scraper.ts
          npx tsx services/scrapers/changesavoisien_scraper.ts
          npx tsx services/scrapers/douane_officielle_scraper.ts
          npx tsx services/scrapers/ibani_scraper.ts
          npx tsx services/scrapers/leman_montblanc_scraper.ts
          npx tsx services/scrapers/lyland_scraper.ts
          npx tsx services/scrapers/migros_scraper.ts
          npx tsx services/scrapers/moneyand_scraper.ts
          npx tsx services/scrapers/revolut_scraper.ts
          npx tsx services/scrapers/telexoo_scraper.ts
          npx tsx services/scrapers/wise_scraper.ts